"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { parseLockfile, detectFormat } = require("../src/lockfile");

async function tmpFile(name, content) {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "pkgxray-lock-"));
  const file = path.join(dir, name);
  await fs.writeFile(file, content);
  return file;
}

test("detectFormat recognises all four formats", () => {
  assert.equal(detectFormat("package-lock.json"), "npm");
  assert.equal(detectFormat("/abs/package-lock.json"), "npm");
  assert.equal(detectFormat("yarn.lock"), "yarn");
  assert.equal(detectFormat("pnpm-lock.yaml"), "pnpm");
  assert.equal(detectFormat("pnpm-lock.yml"), "pnpm");
  assert.equal(detectFormat("package.json"), "package-json");
  assert.equal(detectFormat("Gemfile.lock"), null);
});

test("parses npm v3 lockfile (packages key)", async () => {
  const lock = await tmpFile("package-lock.json", JSON.stringify({
    name: "demo",
    lockfileVersion: 3,
    packages: {
      "": { name: "demo", version: "1.0.0" },
      "node_modules/lodash": { version: "4.17.21" },
      "node_modules/react": { version: "19.0.0" },
      "node_modules/react/node_modules/scheduler": { version: "0.25.0" }
    }
  }));
  const { format, deps } = await parseLockfile(lock);
  assert.equal(format, "npm");
  assert.equal(deps.size, 3);
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("react@19.0.0"));
  assert.ok(deps.has("scheduler@0.25.0"));
});

test("parses yarn v1 lockfile", async () => {
  const yarn = `# THIS IS AN AUTOGENERATED FILE
lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

"@babel/core@^7.0.0":
  version "7.24.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz"
`;
  const lock = await tmpFile("yarn.lock", yarn);
  const { format, deps } = await parseLockfile(lock);
  assert.equal(format, "yarn");
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("@babel/core@7.24.0"));
});

test("parses pnpm-lock.yaml packages block", async () => {
  const pnpm = `lockfileVersion: '9.0'
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-xxx}
  /@babel/core@7.24.0:
    resolution: {integrity: sha512-xxx}
  /react@19.0.0(react-dom@19.0.0):
    resolution: {integrity: sha512-xxx}
`;
  const lock = await tmpFile("pnpm-lock.yaml", pnpm);
  const { format, deps } = await parseLockfile(lock);
  assert.equal(format, "pnpm");
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("@babel/core@7.24.0"));
  assert.ok(deps.has("react@19.0.0"));
});

test("parses package.json strips version range prefix", async () => {
  const pkg = await tmpFile("package.json", JSON.stringify({
    name: "demo",
    dependencies: { "lodash": "^4.17.21", "react": "~19.0.0" },
    devDependencies: { "typescript": ">=5.6.3" }
  }));
  const { format, deps } = await parseLockfile(pkg);
  assert.equal(format, "package-json");
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("react@19.0.0"));
  assert.ok(deps.has("typescript@5.6.3"));
});

test("dedups deps appearing multiple times", async () => {
  const lock = await tmpFile("package-lock.json", JSON.stringify({
    lockfileVersion: 3,
    packages: {
      "": { name: "demo", version: "1.0.0" },
      "node_modules/a/node_modules/lodash": { version: "4.17.21" },
      "node_modules/b/node_modules/lodash": { version: "4.17.21" }
    }
  }));
  const { deps } = await parseLockfile(lock);
  // Both entries are lodash@4.17.21 — should collapse to 1
  assert.equal(deps.size, 1);
  assert.equal(deps.get("lodash@4.17.21").paths.length, 2);
});
