"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const os = require("node:os");
const path = require("node:path");
const test = require("node:test");
const { parseLockfile, detectFormat, auditLockfile } = require("../src/lockfile");

async function tmpFile(name, content) {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "pkgxray-lock-"));
  const file = path.join(dir, name);
  await fs.writeFile(file, content);
  return file;
}

test("detectFormat recognises all four formats", () => {
  assert.equal(detectFormat("package-lock.json"), "npm");
  assert.equal(detectFormat("/abs/package-lock.json"), "npm");
  assert.equal(detectFormat("yarn.lock"), "yarn");
  assert.equal(detectFormat("pnpm-lock.yaml"), "pnpm");
  assert.equal(detectFormat("pnpm-lock.yml"), "pnpm");
  assert.equal(detectFormat("package.json"), "package-json");
  assert.equal(detectFormat("Gemfile.lock"), null);
});

test("parses npm v3 lockfile (packages key)", async () => {
  const lock = await tmpFile("package-lock.json", JSON.stringify({
    name: "demo",
    lockfileVersion: 3,
    packages: {
      "": { name: "demo", version: "1.0.0" },
      "node_modules/lodash": { version: "4.17.21" },
      "node_modules/react": { version: "19.0.0" },
      "node_modules/react/node_modules/scheduler": { version: "0.25.0" }
    }
  }));
  const { format, deps } = await parseLockfile(lock);
  assert.equal(format, "npm");
  assert.equal(deps.size, 3);
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("react@19.0.0"));
  assert.ok(deps.has("scheduler@0.25.0"));
});

test("npm v3 workspace roots are skipped, not crashed on", async () => {
  // Regression: a monorepo package-lock lists the project's own workspace
  // packages under bare keys ("packages/foo", "apps/bar") with NO node_modules/
  // segment. When such an entry also omits `name` (a workspace app can), the
  // old parser indexed segments[-1] === undefined and threw
  // "Cannot read properties of undefined (reading 'replace')", fail-closing the
  // whole audit. Workspace packages are first-party source, not registry deps,
  // so they must be skipped like the root — never OSV-queried, never a crash.
  const lock = await tmpFile("package-lock.json", JSON.stringify({
    name: "monorepo",
    lockfileVersion: 3,
    packages: {
      "": { name: "monorepo", version: "0.1.0" },
      "apps/proof-example": { version: "0.1.0" },          // no `name` — the crasher
      "packages/doc-core": { name: "@proof/core", version: "0.1.0" },
      "node_modules/@proof/core": { resolved: "packages/doc-core", link: true }, // symlink, no version
      "node_modules/lodash": { version: "4.17.21" }
    }
  }));
  const { deps } = await parseLockfile(lock);
  // Only the real registry dep survives; workspace roots + the link entry drop.
  assert.equal(deps.size, 1);
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(!deps.has("@proof/core@0.1.0"), "workspace package is not a supply-chain dep");
});

test("auditLockfile completes on a workspace lockfile (no fail-closed crash)", async () => {
  const lock = await tmpFile("package-lock.json", JSON.stringify({
    lockfileVersion: 3,
    packages: {
      "": { name: "monorepo", version: "0.1.0" },
      "apps/example": { version: "0.1.0" },
      "packages/lib": { name: "@x/lib", version: "0.1.0" },
      "node_modules/lodash": { version: "4.17.21" }
    }
  }));
  const result = await auditLockfile(lock, { vulnerabilityCheck: false, triageDecisions: false });
  assert.equal(result.worstDecision, "safe");
  assert.equal(result.totalDeps, 1, "only the registry dep is audited");
  assert.equal(result.results[0].name, "lodash");
});

test("parses yarn v1 lockfile", async () => {
  const yarn = `# THIS IS AN AUTOGENERATED FILE
lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"

"@babel/core@^7.0.0":
  version "7.24.0"
  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.24.0.tgz"
`;
  const lock = await tmpFile("yarn.lock", yarn);
  const { format, deps } = await parseLockfile(lock);
  assert.equal(format, "yarn");
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("@babel/core@7.24.0"));
});

test("parses pnpm-lock.yaml packages block", async () => {
  const pnpm = `lockfileVersion: '9.0'
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-xxx}
  /@babel/core@7.24.0:
    resolution: {integrity: sha512-xxx}
  /react@19.0.0(react-dom@19.0.0):
    resolution: {integrity: sha512-xxx}
`;
  const lock = await tmpFile("pnpm-lock.yaml", pnpm);
  const { format, deps } = await parseLockfile(lock);
  assert.equal(format, "pnpm");
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("@babel/core@7.24.0"));
  assert.ok(deps.has("react@19.0.0"));
});

test("parses pnpm v9 (no leading slash, current pnpm 9 default)", async () => {
  // pnpm 9 / lockfileVersion 9.0 dropped the leading slash and lists each dep in
  // both `packages:` and `snapshots:`. Scoped keys are single-quoted. Must NOT
  // parse to zero, and the duplicate across sections must de-dupe.
  const pnpm = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true

packages:

  lodash@4.17.21:
    resolution: {integrity: sha512-a}

  '@scope/evil@1.0.0':
    resolution: {integrity: sha512-b}

  react@19.0.0(react-dom@19.0.0):
    resolution: {integrity: sha512-c}

snapshots:

  lodash@4.17.21: {}

  '@scope/evil@1.0.0': {}

  react@19.0.0(react-dom@19.0.0): {}
`;
  const lock = await tmpFile("pnpm-lock.yaml", pnpm);
  const { deps } = await parseLockfile(lock);
  assert.equal(deps.size, 3, "v9 must not parse to zero and must de-dupe packages/snapshots");
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("@scope/evil@1.0.0"));
  assert.ok(deps.has("react@19.0.0"));
});

test("parses pnpm v6 (leading slash, name@version)", async () => {
  const pnpm = `lockfileVersion: '6.0'
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-a}
  /@scope/evil@1.0.0:
    resolution: {integrity: sha512-b}
`;
  const lock = await tmpFile("pnpm-lock.yaml", pnpm);
  const { deps } = await parseLockfile(lock);
  assert.equal(deps.size, 2);
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("@scope/evil@1.0.0"));
});

test("parses pnpm v5 (leading slash, name/version)", async () => {
  const pnpm = `lockfileVersion: 5.4
packages:
  /lodash/4.17.21:
    resolution: {integrity: sha512-a}
  /@scope/evil/1.0.0:
    resolution: {integrity: sha512-b}
`;
  const lock = await tmpFile("pnpm-lock.yaml", pnpm);
  const { deps } = await parseLockfile(lock);
  assert.equal(deps.size, 2);
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("@scope/evil@1.0.0"));
});

test("package.json npm alias resolves to the REAL published package", async () => {
  const pkg = await tmpFile("package.json", JSON.stringify({
    name: "demo",
    dependencies: { "myalias": "npm:realpkg@^1.2.3" }
  }));
  const { deps } = await parseLockfile(pkg);
  // OSV must vet realpkg@1.2.3, NOT myalias with a garbage version.
  assert.ok(deps.has("realpkg@1.2.3"), "alias resolves to real name+version");
  assert.ok(!deps.has("myalias@npm:realpkg@^1.2.3"));
});

test("yarn berry npm alias vets the real package, not the alias", async () => {
  const yarn = `"aliased@npm:realpkg@^1.0.0":
  version "1.4.2"
  resolved "https://registry.yarnpkg.com/realpkg/-/realpkg-1.4.2.tgz"
`;
  const lock = await tmpFile("yarn.lock", yarn);
  const { deps } = await parseLockfile(lock);
  assert.ok(deps.has("realpkg@1.4.2"), "vets realpkg, not aliased");
  assert.ok(!deps.has("aliased@1.4.2"));
});

test("package.json url/workspace specs are surfaced unresolved, not false-safe", async () => {
  const pkg = await tmpFile("package.json", JSON.stringify({
    name: "demo",
    dependencies: {
      "ws-lib": "workspace:*",
      "cat-lib": "catalog:",
      "tgz-lib": "https://example.com/lib.tgz",
      "git-lib": "git+https://github.com/x/y.git",
      "ok-lib": "^1.0.0"
    }
  }));
  const { deps } = await parseLockfile(pkg);
  // The resolvable one is present with a clean version.
  assert.ok(deps.has("ok-lib@1.0.0"));
  // The unresolvable ones are present but flagged unresolved (no bogus version).
  const unresolved = Array.from(deps.values()).filter((d) => d.unresolved);
  const names = unresolved.map((d) => d.name).sort();
  assert.deepEqual(names, ["cat-lib", "git-lib", "tgz-lib", "ws-lib"]);
});

test("unresolved package.json specs audit as review, not safe", async () => {
  const pkg = await tmpFile("package.json", JSON.stringify({
    name: "demo",
    dependencies: { "ws-lib": "workspace:*" }
  }));
  // No OSV network — vulnerabilityCheck false. The unresolved dep must not be
  // silently counted clean.
  const result = await auditLockfile(pkg, { vulnerabilityCheck: false, triageDecisions: false });
  const ws = result.results.find((r) => r.name === "ws-lib");
  assert.equal(ws.decision, "review");
  assert.equal(ws.unresolved, true);
  assert.equal(result.summary.safe, 0);
});

test("a stored allow NEVER suppresses a fresh OSV block", async () => {
  const pkg = await tmpFile("package.json", JSON.stringify({
    name: "demo",
    dependencies: { "evil": "1.0.0", "fine": "1.0.0" }
  }));
  const triageDecisions = new Map();
  // Attacker drops an `allow` beside the lockfile to neuter the scan.
  triageDecisions.set("evil@1.0.0", {
    name: "evil", version: "1.0.0", decision: "allow", reason: "sneaked in",
    decided_at: "2026-01-01T00:00:00Z"
  });
  triageDecisions.set("fine@1.0.0", {
    name: "fine", version: "1.0.0", decision: "allow", reason: "legit",
    decided_at: "2026-01-01T00:00:00Z"
  });
  // Fresh OSV: evil has a vuln, fine is clean. Index-aligned with the resolved
  // deps in map order: [evil, fine].
  const result = await auditLockfile(pkg, {
    triageDecisions,
    osvResults: [
      { vulns: [{ id: "CVE-2026-0001", aliases: [] }] },
      {}
    ]
  });
  const byName = new Map(result.results.map((r) => [r.name, r]));
  // OSV block wins over the stored allow.
  assert.equal(byName.get("evil").decision, "block", "allow must not hide a fresh OSV vuln");
  assert.equal(byName.get("evil").triaged, true);
  // A clean dep with an allow still reads safe.
  assert.equal(byName.get("fine").decision, "safe");
  assert.equal(result.summary.blocked, 1);
  assert.equal(result.worstDecision, "block");
});

test("parses package.json strips version range prefix", async () => {
  const pkg = await tmpFile("package.json", JSON.stringify({
    name: "demo",
    dependencies: { "lodash": "^4.17.21", "react": "~19.0.0" },
    devDependencies: { "typescript": ">=5.6.3" }
  }));
  const { format, deps } = await parseLockfile(pkg);
  assert.equal(format, "package-json");
  assert.ok(deps.has("lodash@4.17.21"));
  assert.ok(deps.has("react@19.0.0"));
  assert.ok(deps.has("typescript@5.6.3"));
});

test("dedups deps appearing multiple times", async () => {
  const lock = await tmpFile("package-lock.json", JSON.stringify({
    lockfileVersion: 3,
    packages: {
      "": { name: "demo", version: "1.0.0" },
      "node_modules/a/node_modules/lodash": { version: "4.17.21" },
      "node_modules/b/node_modules/lodash": { version: "4.17.21" }
    }
  }));
  const { deps } = await parseLockfile(lock);
  // Both entries are lodash@4.17.21 — should collapse to 1
  assert.equal(deps.size, 1);
  assert.equal(deps.get("lodash@4.17.21").paths.length, 2);
});
